### ISSUE TITLE
Error print hola

### ISSUE THREAD

**Issue by victorfernandezesp** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3#1]
Este error es debido a que el texto "hola" no va entrecomillado
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3/blob/287e4476c1526173d4c44f19200631e1cec27246/ejerciciovictor.py#L3

**Comment by victorfernandezesp** [comment]
Mejoralo

**Comment by JavierPA3** [comment]
Ok

**Comment by JavierPA3** [comment]
Arreglado!
