### ISSUE TITLE
Error printea mal la variable

### ISSUE THREAD

**Issue by victorfernandezesp** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3#2]
La forma correcta de printear seria: `print('hola', variable1)`
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3/blob/287e4476c1526173d4c44f19200631e1cec27246/ejerciciovictor.py#L4

**Comment by victorfernandezesp** [comment]
Mejoralo

**Comment by JavierPA3** [comment]
Ok, por cierto, no se dice 'printea' se dice imprime, ^^
