### ISSUE TITLE
error exit

### ISSUE THREAD

**Issue by victorfernandezesp** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3#3]
para salir del programa debes usar `exit()` y entre parentesis un numero, ya sea un 0 si finaliza bien o un 1,2, 3... si hay un error
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3/blob/287e4476c1526173d4c44f19200631e1cec27246/ejerciciovictor.py#L5

**Comment by victorfernandezesp** [comment]
Mejoralo

**Comment by JavierPA3** [comment]
Ok
