### ISSUE TITLE
Error tabulacion mal hecha

### ISSUE THREAD

**Issue by victorfernandezesp** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3#4]
```
for x in range(3):
print(x)
```

Estaria mal tabulado, esto deberia ser asi:

```
for x in range(3):
    print(x)
```
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3/blob/287e4476c1526173d4c44f19200631e1cec27246/ejerciciovictor.py#L7

**Comment by victorfernandezesp** [comment]
Mejoralo

**Comment by JavierPA3** [comment]
Ok
