### ISSUE TITLE
Completar etiqueta:

### ISSUE THREAD

**Issue by AdrianGM02** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3#5]
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3/blob/0aaf29bc73c2f1931889f43f6495eb4587d252f2/index.html#L10

Se solucionaría añadiendo el número 1 al final de la etiqueta

**Comment by JavierPA3** [comment]
Ok!

**Comment by JavierPA3** [comment]
Arreglado!
