### ISSUE TITLE
Completar etiqueta

### ISSUE THREAD

**Issue by AdrianGM02** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3#8]
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-JavierPA3/blob/0aaf29bc73c2f1931889f43f6495eb4587d252f2/index.html#L13

Falta añadir el numero 3 al final de la etiqueta

**Comment by JavierPA3** [comment]
Ok!
